### ISSUE TITLE
Picker not opening if edittext already has focus!

### ISSUE THREAD

**Issue by chanonly123** [BlackBoxVision/datetimepicker-edittext#3]
Picker not opening if edittext already has focus!

**Comment by JonatanSalas** [comment]
I will review it today!

**Comment by JonatanSalas** [comment]
@chanonly123 this issue it's intended to be fixed by the PR that I have referenced. Take a look at the new library version v0.3.1. Probe it and let me know! By the way, I will close this issue. 

If you see this error is happening again, please, re open it. And I will take it into account as soon as I can!
